# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


TEMPLATE = app
QT += core gui sql
TARGET = BabySteps
DESTDIR = ../x64/Debug
CONFIG += c++11
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
